[project]
name = "htom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "html2text>=2025.4.15",
    "uvicorn>=0.34.2",
]
